name: Blog Log Action

on: [push]

jobs:
  log-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install Pillow
    - name: Run log action
      run: python log_action.py
